version: '2.1'

volumes:
  # PIHOLE
  pihole_config:
  dnsmasq_config:
  # AUDIO
  spotifycache:
  snapcast:
  # HOME ASSISTANT
  ha_config:
  # MQTT
  mosquitto:
  # Zigbee2Mqtt
  zigbee:
services:
  # PIHOLE
  pihole:
    container_name: pihole
    image: pihole/pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - 'pihole_config:/etc/pihole'
      - 'dnsmasq_config:/etc/dnsmasq.d'
    dns:
      - '127.0.0.1'
      - '1.1.1.1'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  # AUDIO
  airplay:
    container_name: airplay
    build: ./airplay
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - snapcast:/var/cache/snapcast

  spotify:
    container_name: spotify
    build: ./spotify
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - spotifycache:/var/cache/raspotify
      - snapcast:/var/cache/snapcast

  snapcast-server:
    container_name: snapserver
    build:
      context: ./snapcast-server
      args:
        SNAPCAST_VERSION: 0.18.1
    restart: always
    ports:
      - 1704:1704
      - 1705:1705
    volumes:
      - snapcast:/var/cache/snapcast

  snapcast-client:
    container_name: snapclient
    build:
      context: ./snapcast-client
      args:
        SNAPCAST_VERSION: 0.18.1
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - snapcast:/var/cache/snapcast

  # BALENA HOME ASSISTANT
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    environment:
      - TZ=Europe/Berlin
    ports:
      - 8123:8123
    volumes:
      - 'ha_config:/config'
    restart: always

  mqtt:
    container_name: mqtt
    image: arm32v6/eclipse-mosquitto
    ports:
      - "1883:1883"
    restart: always
    volumes:
      - 'mosquitto:/mosquitto'

  # ZIGBEE
  zigbee:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: always
    volumes:
      - 'zigbee:/app/data'
    devices:
      - '/dev/ttyACM0:/dev/ttyACM0'
    cap_add:
      - SYS_RAWIO
