version: '2.1'

volumes:
  # BALENA PIHOLE
  pihole_config:
  dnsmasq_config:
  dnscrypt_config:
  # BALENA SOUND
  spotifycache:
  bluetoothcache:
  snapcast:
  # BALENA HOME ASSISTANT
  ha_config:
  # Zigbee2Mqtt
  zigbee:
services:
  # BALENA PIHOLE
  pihole:
    build: ./balena-pihole/pihole
    privileged: true
    volumes:
      - 'pihole_config:/etc/pihole'
      - 'dnsmasq_config:/etc/dnsmasq.d'
    dns:
      - '127.0.0.1'
      - '1.1.1.1'
    network_mode: host

  # set pihole DNS1 and DNS2 service variables to 127.0.0.1#5053 to use dnscrypt-proxy for upstream DNS
  dnscrypt-proxy:
    build: ./balena-pihole/dnscrypt-proxy
    volumes:
      - 'dnscrypt_config:/config'
    ports:
      - '5053:5053/udp'
  # BALENA SOUND
  bluetooth-audio:
    network_mode: host
    restart: always
    build: ./balena-sound/bluetooth-audio
    privileged: true
    labels:
      io.balena.features.dbus: 1
    volumes:
      - bluetoothcache:/var/cache/bluetooth
      - snapcast:/var/cache/snapcast

  airplay:
    build: ./balena-sound/airplay
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: 1
    volumes:
      - snapcast:/var/cache/snapcast

  spotify:
    build: ./balena-sound/spotify
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - spotifycache:/var/cache/raspotify
      - snapcast:/var/cache/snapcast

  fleet-supervisor:
    build: ./balena-sound/fleet-supervisor
    restart: always
    network_mode: host
    privileged: true
    ports:
      - 3000:3000
    labels:
      io.balena.features.supervisor-api: 1

  snapcast-server:
    build:
      context: ./balena-sound/snapcast-server
      args:
        SNAPCAST_VERSION: 0.17.1
    restart: always
    ports:
      - 1704:1704
      - 1705:1705
    volumes:
      - snapcast:/var/cache/snapcast

  snapcast-client:
    build:
      context: ./balena-sound/snapcast-client
      args:
        SNAPCAST_VERSION: 0.17.1
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - snapcast:/var/cache/snapcast

  # BALENA HOME ASSISTANT
  homeassistant:
    build: ./balena-homeassistant/homeassistant
    ports:
      - 8123:8123
    privileged: true
    volumes:
      - 'ha_config:/config'
    restart: always
    devices:
      - '/dev:/dev'

  mqtt:
    image: arm32v6/eclipse-mosquitto
    ports:
      - "1883:1883"
    restart: always

  hass-configurator:
    image: "causticlab/hass-configurator-docker:arm"
    restart: always
    ports:
      - "8124:3218"
    volumes:
      - 'ha_config:/hass-config'
    environment:
      - HC_BASEPATH=/hass-config

  # ZIGBEE
  zigbee:
    image: koenkk/zigbee2mqtt
    restart: always
    privileged: true
    volumes:
      - 'zigbee:/app/data'
    devices:
      - '/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B000BE6709A-if00:/dev/zigbee'
