version: '2.1'

volumes:
  spotifycache:
  snapcast:
services:
  airplay:
    container_name: airplay
    build: ./airplay
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - snapcast:/var/cache/snapcast

  spotify:
    container_name: spotify
    build: ./spotify
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - spotifycache:/var/cache/raspotify
      - snapcast:/var/cache/snapcast

  snapcast-server:
    container_name: snapserver
    build:
      context: ./snapcast-server
    restart: always
    ports:
      - 1704:1704
      - 1705:1705
    volumes:
      - snapcast:/var/cache/snapcast

  snapcast-client:
    container_name: snapclient
    build:
      context: ./snapcast-client
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - snapcast:/var/cache/snapcast
